### ISSUE TITLE
Add channelling circle in front of Karazan for Kiljeaden summon 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#1998]

**Comment by SebastianTanoni** [comment]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/a9d70de6-a3d3-471a-a5e7-f3ed7b112433)

@YakaryBovine For some reason, the channeling circle doesnt appear for Kil'jaeden. My guess is because Sunfury is a faction choice and not the default one? must have to do with the channeling quest init for the little circle

**Comment by SebastianTanoni** [comment]
Its the automatic circle for the channeling quests

**Comment by YakaryBovine** [comment]
Sweet, I'll check it out, thanks for investigating.

**Comment by YakaryBovine** [comment]
Had a look at the issue... This is going to require a pretty significant refactor to Quest code so I'm moving it over to a major version.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/cea8e20afd047c9c215ddf15d659d6efe6d39aa4
