### ISSUE TITLE
Give legion some early form of siege 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2320]
Infernal second attack perhaps 
Change the Fel hound summon to someone siege like? 
Change up burning archer , they are rarely used
have a play 
@vampirika

**Comment by YakaryBovine** [comment]
@Technopig1992 @vampirika Do either of you have intent to do this one?

**Comment by vampirika** [comment]
I thought @Technopig1992 was picking this up with burning archer change whilst I was away. I can make a PR for it though.

Could this get out before the big NA patch? I feel like there is a more pressing need for this and I know there are a lot of big changes still need reviewing for NA

**Comment by YakaryBovine** [comment]
> I thought @Technopig1992 was picking this up with burning archer change whilst I was away. I can make a PR for it though.
> 
> 
> 
> Could this get out before the big NA patch? I feel like there is a more pressing need for this and I know there are a lot of big changes still need reviewing for NA

It's possible he's already taken care of it, not sure. I've assigned you for the present. 

I don't think we can get this ahead of the NA changes because many of those changes are already in dev, and we don't release features straight from main as that is reserved for bug fixes and low-risk balance changes.
