### ISSUE TITLE
Implement a coded replacement for Legion's Dark Summoning abilities

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2468]
Current implementation of Dark Summoning sucks because if you select multiple units, they'll all cast their copy of the spell, which is a total waste because only one will actually do anything. Solution is to code a new one from scratch, and use Channel as the base dummy spell with Unique Cast ticked under Options.

**Comment by SebastianTanoni** [comment]
Dark Summoning Dummy ability: A02T

Dark Summoning actual ability to be cast by code: A00E

**Comment by SavanticIO** [comment]
I'll take a crack at this. :)

**Comment by YakaryBovine** [comment]
Just reassigning to you Sebas so you can make sure this works as you'd want it to.

**Comment by SebastianTanoni** [comment]
Couple of bugs here:

It shouldnt target units with Resistant Skin. 
Because it does, it moves the elites that casts it, which cancels the ability. I think because the code fires when the ability is cast, and not when it is resolved. So the code fires before the ability is put on cooldown AND there is no animation
