### ISSUE TITLE
Warsong buildings cannot cast For the Horde!

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2622]
Warsong doesn't have Bloodlust ability on Lumber Camp and Orgrimmar

**Comment by Tehia** [comment]
I think I'll be able to get it done.

**Comment by Tehia** [comment]
Checked in editor both buildings got ability "for the horde" which gives BL. Checked it also in-game.
I think nothing to be fix here, or I've looking for something else.

**Comment by YakaryBovine** [comment]
> Checked in editor both buildings got ability "for the horde" which gives BL. Checked it also in-game. I think nothing to be fix here, or I've looking for something else.

Just had a quick look. Here's how I tested it:
1. Opened my `appsettings.Zak.json` file and modified the `TestingPlayerSlot` to 5, so that I can play as Warsong. I know that Warsong is 5 because of `PlayerNumbers.txt`.
2. Launched the game via the Test launch setting.
3. Typed "-complete to tame a land" to complete the quest that gives Orgimmar
4. Looked at Orgrimmar: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/52b8d1d6-8c65-4070-99a2-cdd9dee1c894)
5. Confirmed that Orgrimmar can't cast For the Horde

Haven't checked to see what the problem is, but those steps should reproduce the issue.

**Comment by Tehia** [comment]
Diving into it more then, thank you.

**Comment by Ripzss** [comment]
> Checked in editor both buildings got ability "for the horde" which gives BL. Checked it also in-game. I think nothing to be fix here, or I've looking for something else.

So to fix this you would have to look in the Scenario Properties Abilities tab.

**Comment by YakaryBovine** [comment]
> > Checked in editor both buildings got ability "for the horde" which gives BL. Checked it also in-game. I think nothing to be fix here, or I've looking for something else.
> 
> So to fix this you would have to look in the Scenario Properties Abilities tab.

Well, sort of. We actually follow a pattern where all player information is controlled via `Faction` code. Ideally, all Faction-specific abilities (like this one) should be disabled for _all_ players in that Abilities tab. I assume that until recently, this ability was enabled for everyone, but was disabled for everyone in this Issue: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2582

Then, if you go to `FrostwolfSetup.cs`, you'll see this line: `Frostwolf.ModAbilityAvailability(Constants.ABILITY_A0GM_FOR_THE_HORDE_PINK_GREY_MAIN_BUILDINGS, 1);`. That enables For the Horde for Frostwolf specifically. Sebas forgot to add it to Warsong as well, so all you need to do is port that over to `WarsongSetup.cs`.

**Comment by YakaryBovine** [comment]
Just noticed this was broken in 3.10 so this qualifies as necessary for the 3.10 full release.
