### ISSUE TITLE
Kultiras has legion quests?

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#263]
![image](https://user-images.githubusercontent.com/47048283/201415957-a727aa69-ded6-439e-a80a-9c51184703bf.png)

**Comment by TracyTheBoy** [comment]
Could it be that this is caused by the missmtach between the player numbers in the C# version and in the map editor?
I checked your post on discord of April where you posted a Screenshot of all of them and they don't match anymore.

![image](https://user-images.githubusercontent.com/93258020/201440613-113362f7-54f4-40e2-9c13-1d3cd73e88bb.png)

In the pic KulTiras is 23 but in the c# Version it has player number 21. But 21 is wrong and if you change it to 22 because the c# version starts at index 0. I don't get the wrong quests anymore and the colors match too. 
This could be the cause of a lot of problems.

What do you think?

**Comment by YakaryBovine** [comment]
@TracyTheBoy Yep, you were exactly correct.
