### ISSUE TITLE
Remove lumber as a concept from the map

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2746]
- [x] Remove lumber harvesting ability from all workers
- [ ] remove lumber rewards from quests
- [ ] change objectives that require researching a lumber upgrade
- [x] change trading posts ability
- [x] remove shredders

**Comment by YakaryBovine** [comment]
@SebastianTanoni Want me to do the "remove lumber cost from all x" bit? I can automate it.

**Comment by SebastianTanoni** [comment]
@YakaryBovine that would be awesome, there works be literally 0 exceptions

**Comment by YakaryBovine** [comment]
Spin off at #2748

**Comment by YakaryBovine** [comment]
@SebastianTanoni Something else to consider... The real opportunity here is that trees could become destructibles instead of doodads. Doodads are way more performant. Obvious downside is siege weapons not being able to destroy them, but maybe there could be special trees that can be (or just use some other object for walls that need to be destroyed).

**Comment by SebastianTanoni** [comment]
@YakaryBovine absoulutely, although that would be a momumental amount of work, considering there are 10k trees or so, but yes!!

**Comment by YakaryBovine** [comment]
Closed by #2767
