### ISSUE TITLE
Siege Tower Devotion Aura interacts with other Devotion Auras in an exploitable way

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3072]
if its applied before any normal devotion aura and unit then walks into that devotion aura its gonna increase the value from 0.5 (50%) to value of new devotion aura - in this case 2 (200%) of base units armor
works with hero devotion auras too for crazy numbers on high base armor units

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/5c4d5648-8310-491d-ace5-1b983dab3995)

**Comment by YakaryBovine** [comment]
Jeeze this is going to suck!

**Comment by YakaryBovine** [comment]
The gist of the bug is that Devotion Auras giving a percentage bonus interact in a buggy way with any Devotion Aura that gives a flat bonus and applies the same buff.

The solution to this is pretty simple: replace the buff applied by Aura of Protection with something other than Devotion Aura, so that it can't interact with other instances of Devotion Aura in this bugged way.

When we do this, we should also do the following because Aura of Protection is **not** mechanically identical to Devotion Aura.
1. Give Aura of Protection a unique icon
2. Make sure the buff applied by it has the same icon

The alternative to all of this is to just change Aura of Protection to a normal Devotion Aura, so that it doesn't apply a percentage bonus.

**Comment by YakaryBovine** [comment]
Marked as High priority because this is very exploitable.

**Comment by Technopig1992** [comment]
Happy to pick this up

**Comment by YakaryBovine** [comment]
Closed by #3073
