### ISSUE TITLE
Intercontinental Artillery special effect visuals can be manipulated to not show up.

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3075]
The player is able to launch a "nuke" without the visual alert indicator showing up.

@Ripzss knows how :D

**Comment by YakaryBovine** [comment]
Sweet, I'll move this into the "Missing reproduction steps" column and assign it to @Ripzss. Once you've listed the reproduction steps feel free to unassign for someone else to pick up the fix.

**Comment by Technopig1992** [comment]
Replication Steps 

- Get Intercontinental Artillery. 
- Set rally point and notice the nuke animation begins.
- Cast the nuke ability during this time and the casted ability will not show any visuals but will still "launch"

**Comment by YakaryBovine** [comment]
> Replication Steps
> 
>     * Get Intercontinental Artillery.
> 
>     * Set rally point and notice the nuke animation begins.
> 
>     * Cast the nuke ability during this time and the casted ability will not show any visuals but will still "launch"

Brilliant, thank you. When this structure was first implemented it had no Rally Point, so something's changed. Ideally we want to do two things:
1. Remove the Rally Point function
2. Make it so that only ability orders will trigger the nuke animation (i.e. ignore "rally" orders)

I'll move this to Ready and unassign everybody. Only need one person for this!

**Comment by YakaryBovine** [comment]
Just going to have to remake the spell properly so this doesn't recur again.
