### ISSUE TITLE
Voodoo regeneration ability icon(s)

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3131]
The same icon is used when the ability is both active and disabled.

**Comment by YakaryBovine** [comment]
We haven't been worrying about ability on/off icons for abilities like this, because they seem quite hard to get right. Unlike an autocast icon we can't just run it through Button Manager. So let's have a quick chat about this and get a pattern running down in the Wiki before we decide what to do.

Thus leaving it in Triage.

**Comment by Technopig1992** [comment]
Reminder update - a new process has been implemented and added to the wiki on how on/off ability icons are handled . Closing this down
