### ISSUE TITLE
Enslaved Dragon colour system

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#323]
When Dragonmaw builds a Roost or trains a Dragon, it should be coloured according to the region that it's in. Just go with the closest point. 
![image](https://user-images.githubusercontent.com/8995690/202065743-61bf393c-4af5-46f2-a867-9e27b48e06c1.png)
NA: green
SA: red
Blackrock: black
Northrend: blue
Outland: nether
Southern Kalimdor: bronze
Northern Kalimdor: green

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/202272062-e8070bab-59fa-4a65-9c67-59eca2ccce26.png)

If we want to use the proximity system (only certain locations) i have a perfect solution for what happens when you are in between:

Default dragon roost can always train Dragon Riders. So you get whelps only if you are near the locations where dragons are found

**Comment by SebastianTanoni** [comment]
So anywhere else, its just a dragon rider available. But if you build the roost near the critical spots, then you get the option to get a whelp on top
