### ISSUE TITLE
list of buildings/units/researches warranting change

### ISSUE THREAD

**Issue by richardik** [AzerothWarsLR/WarcraftLegacies#684]
Scourge: Skeletal Mastery (vanilla mechanic/gold cost), Improved Orb of Annihilitation (overly pricy, non-exciting effect), Epidemic research (overpriced)
Lordaeron : Siege Camp and its units trained(pierce dmg scorpion has no role), Mage, Silverhand Squire(awful with Exorcism removed), Thunder Eagle(weak for being quest reward), Pegasus Knight(without ground mode, it has anti synergy with huntsmen Ensnare)
Quelthalas: Consortium (only trains 1 unit, should be moved to other casters' building)
Dwarf: Rune Priest (strong but boring, uses 2 spell of Geomancer of Dalaran, together they take away from each other's uniqueness, would rather remove him or change his skillset considerably to focus dwarf on their mech theme)
Legion: Burning Archer(only non-demon unit, felt like a weird standout), Greater Doom Guard(would add rain of fire to them)
Sentinels: Reedemed Highborne(iirc started as a waterwalking unit, now its just discount version of Naga Sea Witch on Illidan), Roost(says it trains chimaeras but it doesnt) or Watcher's Bastion(overall, 4 buildings but most train only 1-2 units, redundant IMO), Maiev spellbook?, 2x Hunt aura(Maiev/Naisha)
Druids: Deadly/Crippling poison researches overlap, Ursoc, Tortolla, Druid of the Talon
Warsong: Shadow Priest, Grom ult, Ignore Pain research(too expensive), Kor'Kron elite long cast time
Frostwolf: Catapult from Tauren Totem
Goblin: Sapper/Gunner no active abilities(sappers could use kamikaze imo :) )
Stormwind: Sabouteur(gimmick unit), Conjurer,
Kultiras: overlap with Druid units (could have something more unique)
Illidan: Naj'entus(bad ultimate), Couatl(boring), Akama(awkward skillset), Illidan(needs new skillset), Power Infusion research is in wrong building
Fel Horde: Demon Gates(some upgrades cost 1000 gold, some 100, dont feel like its finalized mechanic), Incinerate research (expensive)

**Comment by YakaryBovine** [comment]
I think you're correct about the majority of these.

But this doesn't belong as a GitHub issue because issues are for planned work. Unless you're planning on actioning any of this yourself, it's just ordinary player feedback and thus belongs in the feedback channel on Discord.

You can create an issue directly for any of the following:
- A bug
- A clear, unambiguous tooltip or icon issue
- Concrete balance changes (e.g. "halve the damage of Defensive Orbs"). You are able to do this one because you are a balance expert
