### ISSUE TITLE
If creeps destroy a cp, the cp dissapears, and the tower stays there forever

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#738]
![image](https://user-images.githubusercontent.com/47048283/209256431-765f8fc1-4fe4-41dd-a2b4-75d5cf3e50ef.png)

**Comment by YakaryBovine** [comment]
@SebastianTanoni Can you give me reproduction steps? These reproduction steps do not reproduce the bug:
1. Find a Control Point with Neutral Hostile units nearby
2. Type -hp 1 to reduce the Control Point's hit points to 1
4. Change the ownership of the Control Point to Lordaeron with -control 1
5. The Neutral Hostile units should attack the Control Point
6. If the bug exists, the Control Point will be destroyed instead of being transferred to Neutral Hostile
