### ISSUE TITLE
The "The Citadel" quest hasn't been updated to account for Outland changes

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#935]
- [ ] The Description talks about Magtheridon who is no longer in the game
- [ ] The RewardDescription says that it grants Kargath, but Kargath is already trainable without the quest

**Comment by IDeathlordI** [comment]
hello just wanted to say this isn't mentioned here, the reward description should mention it grants access to Gruul after completing because the quest gives you access to train Gruul after completing.
![1](https://user-images.githubusercontent.com/118076121/211027420-1753e976-d525-4ec3-bdd5-c448c0428b7b.jpg)
